site_name: Artificial Image Simulator
repo_url: 'https://github.com/DBernardes/AIS'
repo_name: 'Dbernardes/AIS'


theme:
  name: 'material'
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

  
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [AIS]