"""
Telescope Spectral Response Class
===================================

This class calculates the output flux of an astronomical object as a funtion
of the 1.6 m Perkin-Elmer spectral response.
"""


class Telescope_Spectral_Response:
    """Telescope Spectral Response Class."""

    def __init__(self):
        """Initilize the class."""
        pass

    def apply_telescope_spectral_response(self, star_spectrum, l_init, l_final, l_step):
        """Apply the telescope spectral response.

        This function applies the telescope spectral response on the
        calculated star spectrum

        Parameters
        ----------
        star_spectrum : array like
            Spectrum of the star

        l_init: int
            Initial wavelength in nanometers.

        l_final: int
            Final wavelength in nanometers.

        l_step: int
            Step for the wavelength interval in nanometers.

        Returns
        -------
        star_spectrum : array like
            Spectrum of the star generated by the spectral response of the
            1.6 m Perkin-Elmer telescope
        """
        self.star_spectrum = star_spectrum
        wavelength_interval = range(l_init, l_final, l_step)

        return star_spectrum
