"""
Telescope Spectral Response Class
===================================

This class calculates the output flux of an astronomical object as a funtion
of the 1.6 m Perkin-Elmer spectral response.
"""


class Telescope_Spectral_Response:
    """Telescope Spectral Response Class."""

    def __init__(self):
        """Initilize the class."""
        pass

    def apply_telescope_spectral_response(self, star_spectrum):
        """Apply the telescope spectral response.

        This function applies the telescope spectral response on the
        calculated star spectrum

        Parameters
        ----------
        star_spectrum : array like
            Spectrum of the star

        Returns
        -------
        star_spectrum : array like
            Spectrum of the star generated by the spectral response of the
            1.6 m Perkin-Elmer telescope
        """
        star_spectrum = star_spectrum

        return star_spectrum
