"""
Atmosphere Spectral Response
============================

This class calculates the output flux of an astronomical object as a funtction
of the atmosphere spectral response.
"""


class Atmosphere_Spectral_Response:
    """Atmosphere Spectral Response Class."""

    def __init__(self):
        """Initialize the class."""
        pass

    def apply_atmosphere_spectral_response(self, star_spectrum):
        """Apply the atmosphere spectral response.

        This function applies the atmosphere spectral response on the
        calculated star spectrum

        Parameters
        ----------
        star_spectrum : array like
            Spectrum of the star

        Returns
        -------
        star_spectrum : array like
            Spectrum of the star generated by the spectral response of the
        terrestrial atmosphere.
        """
        star_spectrum = star_spectrum

        return star_spectrum
