# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip        
       pip install poetry
       poetry install        
    - name: Run tests and make cov
      run: |
        poetry run pytest -x tests --cov=AIS
        poetry run coverage html
    - name: Make docs
      run: |
        poetry run sphinx-apidoc -o docs .
        cd docs && make html
      
